### ISSUE TITLE
WP Gatsby in Packagist

### ISSUE THREAD

**Issue by rodrigo-arias** [gatsbyjs/wp-gatsby#1]
Hi Tyler,

Great work with the new WordPress and Gatsby integration. I am excited and I follow closely.

Do you think wp-gatsby will be in Packagist? It would be really useful

Thank you

**Comment by szepeviktor** [comment]
@rodrigo-arias You may use this package right now!

https://github.com/szepeviktor/on-its-way.com/blob/62a5d631bade02593bd4dbfa82730edd0ebba685/composer.json#L39-L42

**Comment by rodrigo-arias** [comment]
@szepeviktor the repository recently moved, but I guess now that it's in Gatsby official account your solution is more than enough. Thank you
