### ISSUE TITLE
GRAPHQL_DEBUG always set as true

### ISSUE THREAD

**Issue by lnikell** [gatsbyjs/wp-gatsby#104]
Hi, I found that there is no way to set "GRAPHQL_DEBUG" as false

![image](https://user-images.githubusercontent.com/2697570/104626317-0db54a00-5696-11eb-8938-554d2d10b0fb.png)

It's set on the plugin level as true in this file
/wp-content/plugins/wp-gatsby/tests/_data/config.php

I'm sure it should not work this way, but if I comment this line everything starts to work as expected 
![image](https://user-images.githubusercontent.com/2697570/104626569-5c62e400-5696-11eb-84d0-786526547809.png)

wp-gatsby - version 0.9.1

**Comment by jasonbahl** [comment]
@lnikell that file (`/wp-content/plugins/wp-gatsby/tests/_data/config.php`) is just included in the tests that run when pull requests are opened. That file is not included at run-time when using the plugin.

**Comment by jasonbahl** [comment]
I would check your `wp-config.php` file to see if `GRAPHQL_DEBUG` was set to true there

**Comment by lnikell** [comment]
@jasonbahl Hi, thank you for the reply. I don’t know exactly why the test file some how affects on the behavior. But I used grep to find any places where that line exist and found it only in that file. And as i mentioned if i remove this line from that test file everything works right. So it looks for me as a bug.

**Comment by jacksellwood** [comment]
Hi there! Did you install wp-gatsby via composer or another package manager? If you create a blank WordPress site and install directly from wordpress.org do you still have this issue?
