### ISSUE TITLE
Graphql endpoint needs to use get_site_url() 

### ISSUE THREAD

**Issue by jonlow** [gatsbyjs/wp-gatsby#11]
When building a link to the graphql endpoint, the `get_site_url()` function needs to be used instead of `get_home_url()`. Here's a line that I needed to change manually to get it to work https://github.com/gatsbyjs/wp-gatsby/blob/master/src/Admin/Preview.php#L111

This is because the wp-graphql endpoint is based on the site url and not the home url. Usually these are the same, but if you change the site url to `http://playground.local/wp` (eg if you use bedrock) then the endpoint will be `http://playground.local/wp/graphql`

**Comment by TylerBarnes** [comment]
@jonlow thanks for bringing this up! There's a fix in https://github.com/gatsbyjs/wp-gatsby/releases/tag/v0.4.11
