### ISSUE TITLE
WP-Gatsby 1.0 update results in PHP error

### ISSUE THREAD

**Issue by therealgilles** [gatsbyjs/wp-gatsby#112]
Updated the plugin and got this:

`[04-Feb-2021 02:40:36 UTC] PHP Fatal error:  require(): Failed opening required '.../wp-content/plugins/wp-gatsby/vendor/composer/../phpunit/phpunit/src/Framework/Assert/Functions.php' (include_path='.:') in .../wp-content/plugins/wp-gatsby/vendor/composer/autoload_real.php on line 66
`

**Comment by therealgilles** [comment]
Hopefully fixed in 1.0.2 :)

**Comment by TylerBarnes** [comment]
This was due to a mix up with our composer dependencies and has been fixed. Apologies for this!
