### ISSUE TITLE
WP-Gatsby v1.0.2 shows up as v1.0.1

### ISSUE THREAD

**Issue by garryburch** [gatsbyjs/wp-gatsby#113]
WP-Gatsby v1.0.2 shows up as v1.0.1

Installed version says 1.0.1

`<?php
/**
 * Plugin Name: WP Gatsby
 * Description: Optimize your WordPress site to be a source for Gatsby sites.
 * Version: 1.0.1
 * Author: GatsbyJS, Jason Bahl, Tyler Barnes
 * Author URI: https://gatsbyjs.org
 * Text Domain: wp-gatsby
 * Domain Path: /languages/
 * Requires at least: 5.4.2
 * Requires PHP: 7.3
 * License: GPL-3
 * License URI: https://www.gnu.org/licenses/gpl-3.0.html
 */`

**Comment by jacksellwood** [comment]
This was an accident and has been fixed in the latest version of WPGatsby.
