### ISSUE TITLE
Where is register_graphql_object_type?

### ISSUE THREAD

**Issue by szepeviktor** [gatsbyjs/wp-gatsby#116]
Called many times
https://github.com/gatsbyjs/wp-gatsby/search?q=register_graphql_object_type

But definition is missing.

**Comment by szepeviktor** [comment]
Found only a method with the same name

https://github.com/gatsbyjs/wp-gatsby/blob/49c08fa859ffc6fe70f383de521c16bde0b5307f/src/ActionMonitor/ActionMonitor.php#L639-L644

**Comment by jacksellwood** [comment]
Thank you for opening this issue; however, this isn't a priority for us now.
