### ISSUE TITLE
View and Preview links can't both work

### ISSUE THREAD

**Issue by moonmeister** [gatsbyjs/wp-gatsby#12]
I recently noticed my view button linked to my WP instance (cms.moonmeister.net) and not my front-end Gatsby site (moonmeister.net). 

![image](https://user-images.githubusercontent.com/2730871/87200824-3c4f0400-c2b2-11ea-801d-c8afd300f4a1.png)

I Went and updated my Site URL to be correct and the view button started to work. However this broke Previews. Because Gatsby Previews rely on the WP Instance that URL must be WP and not the front-end, but changing the Site URL changes the preview URL. Thus the Preview button takes me to the wrong location. 

I'm thinking we just need to modify the Preview button to use the WordPress address. In the meantime I have to make them match for previews to work. 

![image](https://user-images.githubusercontent.com/2730871/87200682-e7ab8900-c2b1-11ea-8f4d-7a907ae33bd6.png)

**Comment by peteluffman** [comment]
Same issue here

**Comment by TylerBarnes** [comment]
I'm moving all current feature request issues to our internal backlog to cleanup GH issues a bit. If anyone feels strongly about this feature please open a request on our new request tracker at https://portal.gatsbyjs.com/gatsby-cloud (or upvote/comment if someone already made one)

Thanks!
