### ISSUE TITLE
Preview not sending ACF custom fields

### ISSUE THREAD

**Issue by nunof07** [gatsbyjs/wp-gatsby#13]
I have opened this issue in the `gatsby-source-wordpress-experimental` repo: https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/48

I now realize this is probably the more appropriate place to put the issue. Apologies.

Any hints regarding the issue?

**Comment by TylerBarnes** [comment]
Hey @nunof07 ! I'm going to close this one as the issue  is upstream. We can track the status in the other issue you opened 👍 Thanks!
