### ISSUE TITLE
Builds Webhook stoped working after no updates. 

### ISSUE THREAD

**Issue by carolburri** [gatsbyjs/wp-gatsby#130]
HI 
Everything worked fine until today and I'm not able to find out why. 

Following Versions are installed: 
Wp: 5.6.0
Wp-Gatsby: 0.9.1
Wp-Grapahwql: 1.1.3

I don't get any errors and I see the update on the 'Action Monitor' but Gatsby Cloud doesn't deploy anymore. Only if I fire manually. 

Last deploy from WP was at the second of February without any Issues. 

Gatbsy Config: 
  "dependencies": {
    "babel-plugin-styled-components": "^1.12.0",
    "dotenv": "^8.2.0",
    "gatsby": "^2.32.3",
    "gatsby-image": "^2.11.0",
    "gatsby-plugin-manifest": "^2.12.0",
    "gatsby-plugin-offline": "^3.10.0",
    "gatsby-plugin-react-helmet": "^3.10.0",
    "gatsby-plugin-react-svg": "^3.0.0",
    "gatsby-plugin-sass": "^3.2.0",
    "gatsby-plugin-sharp": "^2.14.1",
    "gatsby-plugin-styled-components": "^3.10.0",
    "gatsby-plugin-web-font-loader": "^1.0.4",
    "gatsby-source-filesystem": "^2.11.0",
    "gatsby-source-graphql": "^2.14.0",
    "gatsby-transformer-sharp": "^2.12.0",
    "glob": "^7.1.6",
    "prop-types": "^15.7.2",
    "react": "^16.14.0",
    "react-dom": "^16.14.0",
    "react-helmet": "^6.1.0",
    "react-html-parser": "^2.0.2",
    "react-player": "^2.8.2",
    "react-slick": "^0.28.0",
    "sass": "^1.32.7",
    "slick-carousel": "^1.8.1",
    "styled-components": "^5.2.1"
  }

Any help would be great. 
Thanks a lot, 
Cheers, Carol

**Comment by jacksellwood** [comment]
Hi there, the fastest way for us to take a look at this issue is through Gatsby Cloud. Please go to https://gatsbyjs.com/support and open a ticket with your Gatsby Cloud account.
