### ISSUE TITLE
The webhook is triggered also for posts that are excluded in Gatsby config

### ISSUE THREAD

**Issue by KarlBaumann** [gatsbyjs/wp-gatsby#145]
`gatsby-source-wordpress` plugin has a Type parameter which allows to exclude certain post types. This exclude list should be taken into account when triggering web hook.

In the worst case there should be a filter which allows to exclude post types ourselves.

**Comment by jacksellwood** [comment]
Hi @KarlBaumann, this isn't possible since WPGatsby can't fetch gatsby-config.js options. Instead, use this filter to exclude post types from the action monitor: https://github.com/gatsbyjs/wp-gatsby/blob/08ab1214cf4b5596513063023017b0c3922ca5b8/src/ActionMonitor/ActionMonitor.php#L90
