### ISSUE TITLE
Re-saving permalinks or options should trigger an action

### ISSUE THREAD

**Issue by TylerBarnes** [gatsbyjs/wp-gatsby#15]
Since options and settings aren't cached between builds and are refetched each time, we should create a new action type for this (to just refetch non-node data) and send that over to Gatsby. This will probably require work to be done in WPGatsby & `gatsby-source-wordpress-experimental`

**Comment by TylerBarnes** [comment]
This is actually not fully accurate, this should refetch all data BUT only if the permalink structure changes. We need a new action type, something like `RESYNC_ALL_DATA` or whatever 👍

**Comment by jasonbahl** [comment]
closed by #74
