### ISSUE TITLE
modifyMeta() method is not set up to work with Users

### ISSUE THREAD

**Issue by kellenmace** [gatsbyjs/wp-gatsby#17]
In `/src/ActionMonitor/ActionMonitor.php`, the `modifyMeta()` method is hooked to `updated_user_meta`, `added_user_meta` and `deleted_user_meta` (among other hooks). It assumes that the `$object_id` passed in is a post ID though, and does not account for the possibility that `$object_id` is a user ID.

This causes issues downstream –

The `savePost()` method assumes that the `$post_id` param it receives is actually a post ID and tries to call `get_post()` on it. Then the `savePostGuardClauses()` method that it calls assumes that it is receiving a post object and tries to access properties on it that don't exist. Screenshot: https://cloudup.com/c224fPtV-JM

`modifyMeta()` should be refactored to work for both posts and users.

**Comment by jasonbahl** [comment]
closed by #74
