### ISSUE TITLE
[v.1.6.7] Breaking WPGatsby data fetching. 

### ISSUE THREAD

**Issue by HenrijsS** [gatsbyjs/wp-gatsby#200]
Multiple people on https://github.com/gatsbyjs/gatsby/discussions/33856 are experiencing an issue where the latest WPGraphql plugin somehow disables update detection on Gatsby's side.
There's no errors or warnings. 

Only fix for now is v1.6.6. Are there some breaking changes that keeps Gatsby from updating to the new schema? 
I see that both plugins had an update 2 days ago.

**Comment by TylerBarnes** [comment]
I just pushed up WPGatsby v2.0.2 which fixes this. Thanks for the report!
