### ISSUE TITLE
Add filter for dispatch request to allow custom payloads/headers

### ISSUE THREAD

**Issue by earnjam** [gatsbyjs/wp-gatsby#22]
Some build platforms may require a specific body payload or headers (auth token, etc) for triggering the builds. It would be helpful if the request sent from `ActionMonitor->trigger_dispatch()` was filterable to allow adding these. 

The URL can be set in the WordPress admin, but it doesn't currently pass any arguments to `wp_safe_remote_post()`, so it's an empty payload. Would need to add a default arguments array and run that through a filter first.

**Comment by TylerBarnes** [comment]
Thanks for adding this :D Closed in #23
