### ISSUE TITLE
Critical error when updating to 2.3.2 - member function has_cap() on null

### ISSUE THREAD

**Issue by embergardens** [gatsbyjs/wp-gatsby#222]
Updated wp-gatsby to 2.3.2 and wordpress instance crashes with the following error:

`Fatal error: Uncaught Error: Call to a member function has_cap() on null in /www/wp-content/plugins/wp-gatsby/src/ActionMonitor/ActionMonitor.php:111 Stack trace: #0 /wordpress/wp-includes/class-wp-hook.php(307): WPGatsby\ActionMonitor\ActionMonitor->action_monitor_add_role_caps('') #1 /wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(false, Array) #2 /wordpress/wp-includes/plugin.php(474): WP_Hook->do_action(Array) #3 /wordpress/wp-admin/admin.php(175): do_action('admin_init') #4 /wordpress/wp-admin/index.php(10): require_once('/wordpress/wp-a...') #5 {main} thrown in /www/wp-content/plugins/wp-gatsby/src/ActionMonitor/ActionMonitor.php on line 111`

Wordpress Version: 5.9.3
I am using the Members plugin for role management and thought they might be causing the conflict but disabling it didn't seem to resolve the issue.

**Comment by janmei** [comment]
I get this error too, on version 2.3.3. Could you ever resolve it, @embergardens?

**Comment by janmei** [comment]
Ah man, just had a look into the file at the line described in the error. 
```php
		$roles = apply_filters(
			'gatsby_private_action_monitor_roles',
			[
				'editor',
				'administrator',
				'contributor',
				'author',
			]
		);

		foreach( $roles as $the_role ) {
			$role = get_role($the_role);

			if ( ! $role->has_cap( 'read_private_action_monitor_posts' ) ) {
				$role->add_cap( 'read_private_action_monitor_posts' );
			}
			
			if ( ! $role->has_cap( 'edit_others_action_monitor_posts' ) ) {
				$role->add_cap( 'edit_others_action_monitor_posts' );
			}
		}
```

In my Case I deleted the role `author`. The role could then not be found and throws the error. 

Readding the role `author` fixed the error and is now working.

**Comment by embergardens** [comment]
@janmei Coming back to this project for the first time in three months and your fix solved it! Brilliant! Thank you
