### ISSUE TITLE
License: why GPL v3, not MIT?

### ISSUE THREAD

**Issue by utoppo** [gatsbyjs/wp-gatsby#24]
Most of gatsby’s repositories are licensed under MIT or OBSD. Is there any particular reason why this plugin runs under GPL?

Would it be possible to change the license to MIT?

**Comment by TylerBarnes** [comment]
I believe the reason is something along the lines of WordPress GPL v3 license being infectious or something like that 🤔 . I believe @jasonbahl added the license here and will know why it's currently GPL v3.

**Comment by utoppo** [comment]
Thanks @TylerBarnes  for pointing me in the right direction. After doing a bit of research I found the possible reason for the GPL-license. In order to get a plugin listed on wordpress.org it must be compatible with the GNU General Public License v2, or any later version.
