### ISSUE TITLE
Scheduled posts don't trigger build (Gatsby Cloud)

### ISSUE THREAD

**Issue by jacobarriola** [gatsbyjs/wp-gatsby#26]
Repro steps:
* schedule a post
* visit WordPress site to ensure CRON runs after scheduled publish date

Expected results:
* post is published
* build is triggered to Gatsby Cloud

Actual results
* post is published
* no build is triggered

I don't know whether this feature is supported at the moment or whether there's an issue on my end.

Thanks!

**Comment by jacobarriola** [comment]
@TylerBarnes - nudging you so that it pops on your inbox 👀 . I know you were out for a while and are just catching up on things. Thanks!

**Comment by jasonbahl** [comment]
closed by #74
