### ISSUE TITLE
Getting errors when trying to update or publish a post/page

### ISSUE THREAD

**Issue by kosvrouvas** [gatsbyjs/wp-gatsby#29]
I have the latest versions of both: WP GraphQL 0.12.3 and WP Gatsby 0.4.16 (also happend with WP GraphQL 0.12.0)

When trying to update or publish a post I get a Failed to update from Gutenberg, and this in the console:

![Screenshot_11](https://user-images.githubusercontent.com/3307723/93687731-90ebd800-fac8-11ea-88c9-2bc267c704bd.png)

It seems that if one of the plugins is disabled, it works OK. It doesn't matter what plugin is disabled.

**Comment by TylerBarnes** [comment]
Hi @kosvrouvas , sorry for the delayed response here. Can you send a list of which plugins you have active?
Also if you can emanenable WP_DEBUG and check any server error logs that'd be helpful in understanding what might be causing this.

Thanks!
