### ISSUE TITLE
Feature request: Ability to manually trigger a deploy (Perhaps from dashboard?).

### ISSUE THREAD

**Issue by MaSchVam** [gatsbyjs/wp-gatsby#30]
Hello everyone, 

First of all: Thank you for all the great work you guys are doing in developing this ecosystem! 😃

I thought it would be neat, if we had the ability to decisively choose, when we actually want to trigger a deploy from within WordPress. With the current webhook options, builds are being triggered automatically when posts are published or updated. However, for large sites with lots of content, changes to multiple posts (or pages) often need to be done in succession.

If we had a button somewhere (maybe in the dashboard?) that triggered a webhook - this would allow us to essentially 'batch' changes made to multiple posts, into one deploy. This would also prevent build minutes from being wasted accidentally, by forgetful or non-technical content editors.

**Comment by erick-go** [comment]
I second this request..
What I'm looking for in my particular project:
- Build on scheduled publish
- Build on manual button press (like @MaSchVam requested)

Since monthly builds are limited at Gatsby Cloud, and my girlfriend regularly edits posts this would be a nice option..

**Comment by joperron** [comment]
+1 for this and some more...

Right now we use WPGatsby to automatically build our staging site on publish with Netlify and once we're ready to go I trigger a build on Gatsby Cloud manually. This is fine for now as I'm pretty involved, but in the future I would rather not have to do that, and of course would rather not have to teach editors how to publish from Gatsby Cloud. There are plugins available to trigger builds manually but it would be great to have more flexible options baked into to WPGatsby :)

To add to others' requests, perhaps:

- Preview webhook input
- Build on staging webhook input
- Build on production webhook input
- Automatic build radio button options (triggered on changes/publish):
  - Never automatically build
  - Automatically build to staging on changes
  - Automatically build to production on changes
- Trigger builds on production for scheduled posts checkbox
- Red **Deploy all changes to production** button
- **Deploy all changes to staging** button

**Comment by ardiewen** [comment]
If anyone is looking for an immediate solve to this, I disable my build hook in the `wp-gatsby` plugin and installed another plugin called [WP Jamstack Deployments](https://wordpress.org/plugins/wp-jamstack-deployments/)

This gives me the functionality described above with a manual build button in the admin menu bar.

Long term, this would be a great feature to have within WP-Gatsby.

**Comment by TylerBarnes** [comment]
I'm moving all current feature request issues to our internal backlog to cleanup GH issues a bit. If anyone feels strongly about this feature please open a request on our new request tracker at https://portal.gatsbyjs.com/gatsby-cloud (or upvote/comment if someone already made one)

Thanks!
