### ISSUE TITLE
Preview not working for Events (Events Calendar) post type

### ISSUE THREAD

**Issue by james-wfaa** [gatsbyjs/wp-gatsby#31]
Follow-up from a thread in the wp-graphql #gatsby Slack channel on 10/7/2020.

I have a WordPress install set up with a working preview server - it properly iframes the Gatsby Preview Server into WordPress for posts and pages.  But for "events" created by the Tribe Events "Events Calendar" plugin, the preview just shows the standard WordPress preview (even though my Gatsby code is set up to properly handle events in their own template.)

<img width="605" alt="Screen Shot 2020-10-08 at 8 45 35 AM" src="https://user-images.githubusercontent.com/68076996/95467077-a83d1900-0942-11eb-9495-a7247bab34cf.png">

**Comment by jacksellwood** [comment]
Hi James! We'd gladly accept a PR for this, but we're not committing to first-party support for The Events Calendar at this time.
