### ISSUE TITLE
Add menu location UI

### ISSUE THREAD

**Issue by TylerBarnes** [gatsbyjs/wp-gatsby#32]
This will be essential to using this plugin without writing any PHP. This isn't part of near-term plans but should be considered eventually

**Comment by therealgilles** [comment]
WP-Gatsby now has header and footer menu locations, but I cannot find any documentation on how to use them in Gatsby. Any pointer would be appreciated.

**Comment by therealgilles** [comment]
Found the tutorial page: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/tutorials/using-wordpress-menus.md

**Comment by TylerBarnes** [comment]
I'm moving all current feature request issues to our internal backlog to cleanup GH issues a bit. If anyone feels strongly about this feature please open a request on our new request tracker at https://portal.gatsbyjs.com/gatsby-cloud (or upvote/comment if someone already made one)

Thanks!
