### ISSUE TITLE
Garbage collection causing timeouts

### ISSUE THREAD

**Issue by jasonbahl** [gatsbyjs/wp-gatsby#45]
After pairing with @erick-go on this issue: https://github.com/wp-graphql/wp-graphql/issues/1526

We determined that the issue was related to WPGatsby and not WPGraphQL. 

We together narrowed down the issue to the ActionMonitor class, and I continued to dig and discovered the real issue was in the Garbage Collection. 

There were ~32,000 action monitor actions stored, and the garbage collection query would timeout. So when action monitors were being inserted, garbage was trying to be collected, but was failing. 

There are 2 primary issues here:

- we should consider adding an option to let users opt-out of action-monitor (some users have expressed that they do manual builds when they need to vs. triggering builds when actions are logged)
- we should consider adding options for letting users determine when to trigger webhooks: 
  - at each logged action?
  - 1x/hour
  - 1x/day
  - etc
  - Not all sites need their data live _immediately_ and don't want to pay for builds, etc if they don't _need_ them
- we need to better de-dupe the actions we're logging. There were a lot of duplicate actions. Storing action data as terms instead of meta can help here. We can more efficiently query for and check existing actions. 
- we need to more efficiently clean up garbage. We might want to consider bulk SQL DELETE statement for garbage collection. At minimum we should reduce the number of action_monitor posts we query for cleanup (and paginate the queries if needed) and only query for IDs vs querying for the entire posts.

**Comment by hideokamoto** [comment]
We want to choose the Activity monitor feature at least.
The Custom Post is getting heavy and heavy when created or updated posts.

**Comment by emaildano** [comment]
@jasonbahl We just noticed this as well. We saw there were 10k+ posts under the `action_monitor` post type after we started to experience errors during builds. It seems to be a bottleneck.
