### ISSUE TITLE
The Action Monitor post type registry needs to be adjusted

### ISSUE THREAD

**Issue by pmkemper** [gatsbyjs/wp-gatsby#5]
The Action Monitor post type has exclude_from_search set to false, so Action Monitors can show up in the Wordpress site search. I assume that this is not intentional.

See line 987 here: https://github.com/gatsbyjs/wp-gatsby/blob/master/src/ActionMonitor/ActionMonitor.php

**Comment by TylerBarnes** [comment]
Thanks for the report! Definitely not intentional.

**Comment by emaildano** [comment]
I'm not sure if this is related but when I run my queries I sometimes get a Request Failed status on ActionMonitor.

```
 gatsby-source-wordpress  Request failed with status code 502

Error occured while fetching nodes of the "ActionMonitor" type.
```

I've added the [option to exclude the post type](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/plugin-options.md#typetypenameexclude-boolean) in the gatsby-config.js but it should never be queried anyway, right?

```

```

**Comment by TylerBarnes** [comment]
@emaildano I think that's unrelated since the source plugin auto-excludes the action monitor post type. I'm not sure what's producing those errors 🤔 do you have server logs?

**Comment by emaildano** [comment]
@TylerBarnes I didn't have server logs for this but it seems unrelated to maybe resolved. Thanks for following up.
