### ISSUE TITLE
WPGatsby & WPGraphQL fail on newest versions

### ISSUE THREAD

**Issue by pickleat** [gatsbyjs/wp-gatsby#52]
I recently updated my plugins and started to receive this error. I _think_ the immediate solution is to rollback to the versions listed [here](https://github.com/TylerBarnes/using-gatsby-source-wordpress-experimental/tree/master/WordPress/plugins). But I'm sure that WPGatsby <> WPGraphQL always want to work on the newest stable versions.

I'm currently using: 
WPGraphQL 0.14.0
WPGatsby 0.5.4

Happy to provide any other info needed to help debug! 

```
gatsby develop
Using environment config: 'development'
Using environment config: 'development'
success open and validate gatsby-configs - 0.034s
success load plugins - 0.612s
success onPreInit - 0.032s
success initialize cache - 0.012s
success copy gatsby files - 0.039s
success onPreBootstrap - 0.014s

 ERROR

 gatsby-source-wordpress  WPGatsby and WPGraphQL are both outside the accepted version ranges.
visit https://github.com/TylerBarnes/using-gatsby-source-wordpress-experimental/tree/master/WordPress/plugins to download the latest versions.


Reasons:

- WPGraphQL 0.10.0 introduced a large number of changes that required internal source plugin code changes. A big feature is improved support for WordPress previews and improvements to how Menus are handled. 0.10.3 fixed a private post regression that could cause cold builds to fail.

    V0.11.0 introduced breaking changes, but none that will affect Gatsby users. https://github.com/wp-graphql/wp-graphql/pull/1407

    Head to https://github.com/wp-graphql/wp-graphql/releases/tag/v0.10.0 for more information on upgrading.

- WPGatsby 0.4.14 supports WPGraphQL 0.10.3. Version 0.4.13 and before had a bug where making a published post into a draft wouldn't delete the post in Gatsby.

not finished createSchemaCustomization - 1.011s
```

**Comment by pickleat** [comment]
Downgrading to: 
WPGraphQL 0.13.1
WPGatsby 0.4.17

Gave a similar error: 
```
Your remote version of WPGraphQL is not within the accepted range (>=0.10.3 <0.13.0).
	Download v >=0.10.3 <0.13.0 at https://github.com/wp-graphql/wp-graphql/releases
```
Trying 0.13.0 next.

**Comment by pickleat** [comment]
0.13.0 didn't work, but [0.12.3](https://github.com/wp-graphql/wp-graphql/releases/tag/v0.12.3)

**Comment by lqze** [comment]
Do you have the latest version of `gatsby-source-wordpress-experimental`?

**Comment by zamson** [comment]
It works for me when upgrading `gatsby-source-wordpress-experimental` to the latest version

**Comment by TylerBarnes** [comment]
Hi there, this is an intentional error since the source plugin only supports limited versions of each remote dependency at any time. The error message has been improved in more recent releases to give you a better understanding of what's going on and what your next steps are.

**Comment by TylerBarnes** [comment]
To be clear, you need to upgrade your version of gatsby-source-wordpress-experimental 👍
