### ISSUE TITLE
Wordpress site crashes on v0.6.0 - Parse error: syntax error, unexpected ')' in wp-gatsby/src/Admin/Preview.php on line 169

### ISSUE THREAD

**Issue by somghosh** [gatsbyjs/wp-gatsby#54]
Wordpress site fails upon installing the latest version of WPGatsby plugin  v0.60.0 (commit sha = af4eff661878475967f3ad7f5533b178d72e0fe8)

I get the error as follows

```
Parse error: syntax error, unexpected ')' in /var/www/html/wordpress/wp-content/plugins/wp-gatsby/src/Admin/Preview.php on line 169
There has been a critical error on your website. Please check your site admin email inbox for instructions.

Learn more about debugging in WordPress.

```

My Wordpress version info:
Version	5.5.3
Site Language	en_US
User Language	en_US

**Comment by asifaziz01** [comment]
I am getting the same error when I installed and activated the plugin today.

**Comment by TylerBarnes** [comment]
Thanks for letting us know, I'll have a patch out for this later today

**Comment by TylerBarnes** [comment]
As we move towards a stable release we'll be adding more tests and GH actions that prevent this kind of thing from happening. For now I've hotfixed the issue in v0.6.1. Thanks for reporting this!
