### ISSUE TITLE
Draft preview not loading on list view

### ISSUE THREAD

**Issue by hazuremon** [gatsbyjs/wp-gatsby#65]
Hi Tyler,

Thanks for the latest update on improving WP preview, I notice there is one more condition where WordPress preview is not loading:

- Draft preview request on Posts list view (/wp-admin/edit.php) will stuck at Loading Preview screen, with no build being trigger in Gatsby Cloud.

WP-Gatsby 0.6.7, gatsby-source-wordpress-experimental: 3.3.1

Thank you!

**Comment by hazuremon** [comment]
Above issue still seems to remain unresolved, is there plan to support WP preview that is triggered from the Posts listing page? 

Right now, WP preview from posts listing page will stay at loading screen with PREVIEW_PAGE_UPDATED_BUT_NOT_YET_DEPLOYED status returned in console log. Gatsby cloud does not seem to receive the preview request with no build status.

WP-Gatsby v.1.0.6, Gatsby v3.1.0, Gatsby-source-wordpress v5.1.0

**Comment by hazuremon** [comment]
To replicate:

1. Go to Posts listing page (/wp-admin/edit.php)
2. Find a Draft post
3. Click on "Preview"

<img width="266" alt="Screen Shot 2021-03-19 at 3 02 24 PM" src="https://user-images.githubusercontent.com/1413953/111846546-4c4cc800-88c4-11eb-860b-fd080aeb6370.png">

**Comment by jacksellwood** [comment]
Hi there, clicking "Preview" from the `edit.php` (post list) in wp-admin isn't support right now. It's on our radar, and this is an improvement we'd like to make in the future. In the meantime, clicking into the post itself and then choosing "Preview" will work.
