### ISSUE TITLE
Code to generate Gatsby Preview JWT Secret running on every request

### ISSUE THREAD

**Issue by kellenmace** [gatsbyjs/wp-gatsby#7]
I have a Trellis/Bedrock project that locks down access to the unix `/dev/urandom` pseudorandom number generator file (and other files on the filesystem) by default.

When I have WPGatsby installed, it does this:

- Tries to get the `preview_jwt_secret` setting value.
- If the setting value does not exist, it uses the `RandomLib` library to try to generate one.
- `RandomLib` checks whether the `/dev/urandom` file exists, but since it is not accessible, this warning is thrown:

```
Exception has occurred.
Warning: file_exists(): open_basedir restriction in effect. File(/dev/urandom) is not within the allowed path(s): (/srv/www/:/tmp)
```

Here is a screenshot showing the issue: https://cloudup.com/cZCgIaYb6sd

`RandomLib` does use the `@` prefix to account for that and silence the warning, like this (`@file_exists(static::$file);`), but when I use XDebug, it still breaks on that warning 100% of the time, which can get annoying during debugging. Maybe a try/catch block could be used to make sure `/dev/urandom` is readable before attempting to use `RandomLib`?

Also, it seems to me like the code to try to generate this secret should only be run when:

- The user is on the WPGatsby Settings page.
- No secret exists.
- The user has checked the `Enable Gatsby Preview?` box, indicating that they want to opt in to using Gatsby Preview.

Currently though, it is run on every request.

Thanks for the great work on this plugin! 🙌

**Comment by TylerBarnes** [comment]
This was fixed in #74
