### ISSUE TITLE
Allow multiple webhooks to be triggered

### ISSUE THREAD

**Issue by jooola** [gatsbyjs/wp-gatsby#76]
Hello, I would like to trigger multiple webhooks (at least 2) in order to build both staging and production.
Any chances that wp gatsby plugin handle this ?

**Comment by TylerBarnes** [comment]
Yup :) you can add a comma separated list the webhook option - we haven't documented this previously because I couldn't think of a good reason outside of our internal tests for this feature. But you have a great reason

**Comment by jooola** [comment]
Great thanks !
