### ISSUE TITLE
Fatal error installing plugin

### ISSUE THREAD

**Issue by elliotkidd** [gatsbyjs/wp-gatsby#8]
Plugin version: 0.4.5

Fatal error: Uncaught Error: Class 'WPGatsby\Admin\Settings' not found in (...)wp-content/plugins/wp-gatsby/wp-gatsby.php:162

**Comment by TylerBarnes** [comment]
Hi @elliotkidd , thanks for opening this issue. this was due to a bug that occurs when WPGatsby was installed but WPGraphQL wasn't yet installed. Update to the latest (`v0.4.8`) for a fix!
