### ISSUE TITLE
Hide Action Monitor menu

### ISSUE THREAD

**Issue by jooola** [gatsbyjs/wp-gatsby#97]
A new 'Action Monitor' menu showed up in my WP, and I was looking for a way to hide it from everyone, even for admins.

![image](https://user-images.githubusercontent.com/19195485/102690207-20a63d00-4204-11eb-80ae-2d842edfc381.png)

wp-graphql version 1.0.3
wp-gatsby version 0.9.1

Any chances this can be set in the settings ?

**Comment by TylerBarnes** [comment]
Hey there, this is only visible when `GRAPHQL_DEBUG` is set to true - to hide this turn off WPGraphQL debug mode.
