### ISSUE TITLE
Page post previews issue

### ISSUE THREAD

**Issue by EmyFernanda** [gatsbyjs/wp-gatsby#99]
When clicking preview from a page post the following error occurs:
![1608332580819_regional_screenshot](https://user-images.githubusercontent.com/22663991/102800382-a4793a00-4368-11eb-9eae-c785a8705257.png)

After looking into the pages creation I can see that the ID is being included in the context, however we have about 15 pages that are not being built programmatically and is being built on Gatsby side, so these pages are being excluded, including the homepage:
![1608320863652_regional_screenshot](https://user-images.githubusercontent.com/22663991/102800582-edc98980-4368-11eb-8cd6-5353dd84b68f.png)

Could that be the issue? If so how can we workaround this?

FYI: Blog Posts and KB Posts previews works fine since it's all built programmatically and not on Gatsby side.

**Comment by jasonbahl** [comment]
@EmyFernanda you need to query and pass the `id` of each WordPress post (page, custom post) through to context. I believe there will be problems if the `id` (different from `databaseId`) is not passed.

**Comment by EmyFernanda** [comment]
That fixed, thanks!
